# Generated by Django 4.2.2 on 2023-06-08 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('rec_id', models.IntegerField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('rec_id', models.IntegerField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=255)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_application_product', to='sft.loanapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('rec_id', models.IntegerField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='sft.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('rec_id', models.IntegerField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('loan_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_application_contract', to='sft.loanapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
